name: CI/CD SafeAnimals

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # --- BACKEND ---
    - name: Instalar dependencias del backend
      working-directory: ./backend
      run: npm install

    - name: Verificar sintaxis del backend (node -c)
      working-directory: ./backend
      run: node -c app.js

    # --- FRONTEND ---
    - name: Instalar dependencias del frontend
      working-directory: ./frontend
      run: npm install

    - name: Build del frontend
      working-directory: ./frontend
      run: npm run build
